FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /app/InfrastructureAutomationControlPlane /app/cmd/

FROM golang:1.24.6-alpine

WORKDIR /
COPY --from=builder /app/InfrastructureAutomationControlPlane /InfrastructureAutomationControlPlane
COPY --from=builder /app/config /var/config

EXPOSE 2963
CMD ["/InfrastructureAutomationControlPlane"]
